create table links (
  id bigint generated by default as identity primary key,
  title text not null,
  url text not null,
  created_at timestamp with time zone default now()
);

alter table links enable row level security;

-- 所有人可以读取链接
create policy "public read links" on links for select using (true);

-- **只有登录的用户（你的Supabase账号）可以插入、删除**
create policy "authenticated can insert" on links for insert to authenticated using (true);
create policy "authenticated can delete" on links for delete to authenticated using (true);
